fix(spmd): fix build failure due to redefinition
Clang build breaks with the following warning:

  |  In file included from services/std_svc/spmd/spmd_logical_sp.c:15:
  |  include/services/el3_spmd_logical_sp.h:15:38: error: redefinition of
  |    typedef 'spmd_spm_core_context_t' is a C11 feature [-Werror,-Wtypedef-redefinition].
  |     15 | typedef struct spmd_spm_core_context spmd_spm_core_context_t;
  |        |                                      ^
  |  services/std_svc/spmd/spmd_private.h:58:3: note: previous definition is here
  |     58 | } spmd_spm_core_context_t;
  |        |   ^
  |    CC      services/std_svc/std_svc_setup.c
  |  1 error generated.
  |  In file included from services/std_svc/spmd/spmd_main.c:35:
  |  services/std_svc/spmd/spmd_private.h:58:3: error: redefinition of typedef
  |    'spmd_spm_core_context_t' is a C11 feature [-Werror,-Wtypedef-redefinition]
  |     58 | } spmd_spm_core_context_t;
  |        |   ^
  |  include/services/el3_spmd_logical_sp.h:15:38: note: previous definition is here
  |     15 | typedef struct spmd_spm_core_context spmd_spm_core_context_t;
  |        |                                      ^
  |  1 error generated.

A structure 'spmd_spm_core_context_t' defined in 'spmd_private.h' is
also declared in 'el3_spmd_logical_sp.h' as it is used in a couple of
function declarations. These function declarations can be moved to
spmd_private.h as they are not needed elsewhere.

Change-Id: Ic6b9a277abe00cb7129f671570abf7255be62dfa
Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>