fix(libc): remove __Nonnull type specifier
Clang's nullability completeness checks were triggered after adding
the _Nonnull specifier to one function. Removing it prevents Clang
from flagging atexit() for missing a nullability specifier.

 include/lib/libc/stdlib.h:25:25: error: pointer is missing a
 nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
 [-Werror,-Wnullability-completeness]
    25 | extern int atexit(void (*func)(void));

This change ensures compliance with the C standard while preventing
unexpected build errors.

Change-Id: I2f881c55b36b692d22c3db22149c6402c32e8c3e
Signed-off-by: Manish V Badarkhe <Manish.Badarkhe@arm.com>